name: ci

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: windows-latest
    steps:
      - name: Configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: Configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests
        run: go test -v ./...
